created and added context to universities
sustainers/academic-map pull request #5
Opened 2023-10-24 17:15 UTC by Victorybrown

- Duke University
- Rochester Institute of Technology
- University of Vermont
- University of Michigan

2023-10-24 17:18 UTC, RichardLitt requested changes
A good start! Some comments.

2023-10-24 17:18 UTC, RichardLitt commented on universities/university-of-missouri.md
> -# University of Missouri
What's going on here?

2023-10-24 17:18 UTC, RichardLitt commented on universities/university-of-vermont.md
> +title: "University of Vermont"
We already have this in a PR. Can you check that version against this and see what you could've done differently?

2023-10-24 17:18 UTC, RichardLitt commented on universities/university-of-michigan.md
> +-
What's going on here?

2023-10-27 13:25 UTC, RichardLitt commented
@Victorybrown I think one PR per file will work easier. Can you do that? :)

2023-10-27 14:03 UTC, Victorybrown commented
Okay, will do that

2023-11-10 22:05 UTC, RichardLitt commented
Let's split this out into new PRs. Can you do that? 

Here are some steps to help: 

1. `git checkout main` - go to the main branch.
2. And then `git pull origin main` - pull changes. 
2. `git checkout -b new-branch` - Make a new branch. Replace `new-branch` with the name of the university.
3. `git checkout academic-map-two -- universities/university-of-colorado.md` - this should checkout the file from this PR. Then, edit the file and save it. 
4. `git push origin new-branch` - push it up and make a new PR.

Make sense?

2023-11-10 22:05 UTC, closed without merging